Cleanup

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -3,151 +3,150 @@
 # `bootstrap` installs things.
 #
 
-# Go up one level
+# Go up one level.
 cd "$(dirname "$0")/.."
 
-# Get the current directory path
+# Get the current directory path.
 DOTFILES_ROOT=$(pwd -P)
 
-# Exit if any subcommand or pipeline returns a non-zero status.
+# Exit if any subcommand or pipeline returns a non-zero status..
 set -e
 
 echo ''
 
-# Function to print a "info" message
+# Function to print a "info" message.
 info () {
-  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+	printf "\r  [ \033[00;34m..\033[0m ] $1\n"
 }
 
-# Function to print a "user" message
+# Function to print a "user" message.
 user () {
-  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+	printf "\r  [ \033[0;33m??\033[0m ] $1\n"
 }
 
-# Function to print a "success" message
+# Function to print a "success" message.
 success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
 }
 
-# Function to print a "fail" message
+# Function to print a "fail" message.
 fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
+	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+	echo ''
+	exit
 }
 
 setup_gitconfig () {
-  # Check if `gitconfig.local.symlink` is missing
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
-    info 'setup gitconfig'
+	# Check if `gitconfig.local.symlink` is missing.
+	if ! [ -f git/gitconfig.local.symlink ]
+	then
+		info 'setup gitconfig'
 
-    git_credential='osxkeychain'
+		git_credential='osxkeychain'
 
-    user ' - What is your GitHub author name?'
-    read -e git_authorname
-    user ' - What is your GitHub author email?'
-    read -e git_authoremail
+		user ' - What is your GitHub author name?'
+		read -e git_authorname
+		user ' - What is your GitHub author email?'
+		read -e git_authoremail
 
-    # Create `gitconfig.local.symlink` based on the example file
-    # with [user.name], [user.email] and [credential.helper]
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
+		# Create `gitconfig.local.symlink` based on the example file
+		# with [user.name], [user.email] and [credential.helper].
+		sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
 
-    success 'gitconfig'
-  fi
+		success 'gitconfig'
+	fi
 }
 
 link_file () {
-  local src=$1 dst=$2
+	local src=$1 dst=$2
 
-  local overwrite= backup= skip=
-  local action=
+	local overwrite= backup= skip=
+	local action=
 
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-  then
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
-      local currentSrc="$(readlink $dst)"
+	if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+	then
+		if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
+		then
+			local currentSrc="$(readlink $dst)"
 
-      if [ "$currentSrc" == "$src" ]
-      then
-        skip=true;
-      else
-        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
-        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
+			if [ "$currentSrc" == "$src" ]
+			then
+				skip=true;
+			else
+				user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
+				[s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+				read -n 1 action
 
-        case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
-        esac
-      fi
-    fi
+				case "$action" in
+					o )
+						overwrite=true;;
+					O )
+						overwrite_all=true;;
+					b )
+						backup=true;;
+					B )
+						backup_all=true;;
+					s )
+						skip=true;;
+					S )
+						skip_all=true;;
+					* )
+						;;
+				esac
+			fi
+		fi
 
-    overwrite=${overwrite:-$overwrite_all}
-    backup=${backup:-$backup_all}
-    skip=${skip:-$skip_all}
+		overwrite=${overwrite:-$overwrite_all}
+		backup=${backup:-$backup_all}
+		skip=${skip:-$skip_all}
 
-    if [ "$overwrite" == "true" ]
-    then
-      rm -rf "$dst"
-      success "removed $dst"
-    fi
+		if [ "$overwrite" == "true" ]
+		then
+			rm -rf "$dst"
+			success "removed $dst"
+		fi
 
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
-    fi
+		if [ "$backup" == "true" ]
+		then
+			mv "$dst" "${dst}.backup"
+			success "moved $dst to ${dst}.backup"
+		fi
 
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
-    fi
-  fi
+		if [ "$skip" == "true" ]
+		then
+			success "skipped $src"
+		fi
+	fi
 
-  if [ "$skip" != "true" ] # "false" or empty
-  then
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
-  fi
+	if [ "$skip" != "true" ] # "false" or empty
+	then
+		ln -s "$1" "$2"
+		success "linked $1 to $2"
+	fi
 }
 
 install_dotfiles () {
-  info 'installing dotfiles'
+	info 'installing dotfiles'
 
-  local overwrite_all=false backup_all=false skip_all=false
+	local overwrite_all=false backup_all=false skip_all=false
 
-  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
-  do
-    dst="$HOME/.$(basename "${src%.*}")"
-    link_file "$src" "$dst"
-  done
+	for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
+	do
+		dst="$HOME/.$(basename "${src%.*}")"
+		link_file "$src" "$dst"
+	done
 }
 
 setup_gitconfig
 install_dotfiles
 
-# Install and setup Homebrew
 info "installing dependencies"
 
 if source bin/dot | while read -r data; do info "$data"; done
 then
-  success "dependencies installed"
+	success "dependencies installed"
 else
-  fail "error installing dependencies"
+	fail "error installing dependencies"
 fi
 
 echo ''
