Resolve ShellCheck warnings

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -9,51 +9,51 @@ cd "$(dirname "$0")/.."
 # Get the current directory path.
 DOTFILES_ROOT=$(pwd -P)
 
-# Exit if any subcommand or pipeline returns a non-zero status..
+# Exit if any subcommand or pipeline returns a non-zero status.
 set -e
 
 echo ''
 
 # Function to print a "info" message.
 info () {
-	printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+	printf "\\r  [ \\033[00;34m..\\033[0m ] %s\\n" "$1"
 }
 
 # Function to print a "user" message.
 user () {
-	printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+	printf "\\r  [ \\033[0;33m??\\033[0m ] %s\\n" "$1"
 }
 
 # Function to print a "success" message.
 success () {
-	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+	printf "\\r\\033[2K  [ \\033[00;32mOK\\033[0m ] %s\\n" "$1"
 }
 
 # Function to print a "fail" message.
 fail () {
-	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+	printf "\\r\\033[2K  [\\033[0;31mFAIL\\033[0m] %s\\n" "$1"
 	echo ''
-	exit
+	exit 1
 }
 
 setup_gitconfig () {
 	# Check if `gitconfig.local.symlink` is missing.
 	if ! [ -f git/gitconfig.local.symlink ]
 	then
-		info 'setup gitconfig'
+		info 'Setup .gitconfig'
 
 		git_credential='osxkeychain'
 
 		user ' - What is your GitHub author name?'
-		read -e git_authorname
+		read -r -e git_authorname
 		user ' - What is your GitHub author email?'
-		read -e git_authoremail
+		read -r -e git_authoremail
 
 		# Create `gitconfig.local.symlink` based on the example file
 		# with [user.name], [user.email] and [credential.helper].
 		sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
 
-		success 'gitconfig'
+		success '.gitconfig setup'
 	fi
 }
 
@@ -75,7 +75,7 @@ link_file () {
 			else
 				user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
 				[s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-				read -n 1 action
+				read -r -n 1 action
 
 				case "$action" in
 					o )
@@ -103,30 +103,30 @@ link_file () {
 		if [ "$overwrite" == "true" ]
 		then
 			rm -rf "$dst"
-			success "removed $dst"
+			success "Removed $dst"
 		fi
 
 		if [ "$backup" == "true" ]
 		then
 			mv "$dst" "${dst}.backup"
-			success "moved $dst to ${dst}.backup"
+			success "Moved $dst to ${dst}.backup"
 		fi
 
 		if [ "$skip" == "true" ]
 		then
-			success "skipped $src"
+			success "Skipped $src"
 		fi
 	fi
 
 	if [ "$skip" != "true" ] # "false" or empty
 	then
 		ln -s "$1" "$2"
-		success "linked $1 to $2"
+		success "Linked $1 to $2"
 	fi
 }
 
 install_dotfiles () {
-	info 'installing dotfiles'
+	info 'Installing dotfiles'
 
 	local overwrite_all=false backup_all=false skip_all=false
 
@@ -140,13 +140,13 @@ install_dotfiles () {
 setup_gitconfig
 install_dotfiles
 
-info "installing dependencies"
+info 'Installing dependencies'
 
 if source bin/dot | while read -r data; do info "$data"; done
 then
-	success "dependencies installed"
+	success 'Dependencies installed'
 else
-	fail "error installing dependencies"
+	fail 'Error installing dependencies'
 fi
 
 echo ''
